if(EXISTS "/Users/rahulanand/Desktop/projects/cpp_programs/moderncpp/type-erasure/runTests[1]_tests.cmake")
  include("/Users/rahulanand/Desktop/projects/cpp_programs/moderncpp/type-erasure/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
